In [22]:
import numpy as np
import pandas as pd

In [2]:
def f(x):
  return np.exp(x) - np.log(x)

In [3]:
def fd(x):
  return np.exp(x) - (1/x)

In [4]:
x0 = 1.5
eta = 0.01
print(f'x = {x0}, f(x)-{f(x0)}')
for i in range(100):
  x1 = x0 - eta * fd(x0)
  print(f'x = {x1}, f(x)-{f(x1)}')
  x0=x1

x = 1.5, f(x)-4.0762239622299
x = 1.461849775963286, f(x)-3.934229356483592
x = 1.4255511045357447, f(x)-3.805591409611499
x = 1.3909644365935732, f(x)-3.6887266432622425
x = 1.3579664531185673, f(x)-3.582289934909541
x = 1.326447622675889, f(x)-3.4851311153123112
x = 1.2963102006225906, f(x)-3.396260724783285
x = 1.26746657712878, f(x)-3.3148227475707297
x = 1.2398379031800468, f(x)-3.240072718375354
x = 1.213352940004547, f(x)-3.171360004570204
x = 1.1879470894994015, f(x)-3.1081133632342435
x = 1.1635615723707942, f(x)-3.0498290878890386
x = 1.1401427276567169, f(x)-2.996061219089067
x = 1.117641412642213, f(x)-2.94641341175775
x = 1.0960124863141376, f(x)-2.9005321415328984
x = 1.075214362733116, f(x)-2.8581010002490412
x = 1.0552086232422573, f(x)-2.8188358826457147
x = 1.0359596784463254, f(x)-2.7824809064881273
x = 1.0174344725016795, f(x)-2.748804939457108
x = 0.9996022235468174, f(x)-2.717598630564856
x = 0.9824341951444636, f(x)-2.688671863078379
x = 0.9659034944512859, f(x)-2.661851561175238
x = 0.9499848935209294, f(x)-2.6369797947129285
x = 0.9346546707114541, f(x)-2.6139121362432665
x = 0.9198904696338983, f(x)-2.5925162322649298
x = 0.9056711734637717, f(x)-2.572670557079069
x = 0.8919767927569825, f(x)-2.554263322802454
x = 0.8787883651780735, f(x)-2.5371915233393247
x = 0.8660878657713244, f(x)-2.5213600936041396
x = 0.8538581265920157, f(x)-2.506681168169955
x = 0.8420827646721979, f(x)-2.4930734259075313
x = 0.8307461174277546, f(x)-2.4804615091708078
x = 0.8198331847255393, f(x)-2.468775507748797
x = 0.8093295769243105, f(x)-2.457950499201327
x = 0.7992214682838922, f(x)-2.4479261383737607
x = 0.7894955552057832, f(x)-2.4386462898824233
x = 0.7801390188272513, f(x)-2.4300586982087724
x = 0.7711394915414075, f(x)-2.42211469076193
x = 0.7624850270592037, f(x)-2.4147689098863885
x = 0.754164073666881, f(x)-2.4079790703215935
x = 0.7461654503650609, f(x)-2.401705739076399
x = 0.7384783256042395, f(x)-2.3959121350754735
x = 0.731092198356576, f(x)-2.390563946276114
x = 0.7239968812861428, f(x)-2.3856291622501824
x = 0.7171824857997012, f(x)-2.381077920483654
x = 0.7106394087779777, f(x)-2.376882364870811
x = 0.7043583208036752, f(x)-2.37301651507599
x = 0.6983301557173366, f(x)-2.3694561456067484
x = 0.6925461013458947, f(x)-2.3661786735915835
x = 0.6869975912614887, f(x)-2.3631630543855966
x = 0.6816762974400287, f(x)-2.3603896842411136
x = 0.6765741237001636, f(x)-2.3578403093792124
x = 0.6716831998138457, f(x)-2.3554979408841463
x = 0.6669958761896303, f(x)-2.353346774917289
x = 0.6625047190392722, f(x)-2.3513721178118017
x = 0.6582025059470907, f(x)-2.3495603156649176
x = 0.6540822217700045, f(x)-2.347898688092653
x = 0.6501370548040993, f(x)-2.346375465852731
x = 0.6463603931610842, f(x)-2.3449797320765366
x = 0.6427458213050272, f(x)-2.3437013668806155
x = 0.6392871167063413, f(x)-2.3425309951534183
x = 0.6359782465761054, f(x)-2.3414599373341654
x = 0.6328133646494752, f(x)-2.3404801630185204
x = 0.62978680799215, f(x)-2.3395842472406625
x = 0.6268930938086276, f(x)-2.3387653292937536
x = 0.6241269162353149, f(x)-2.3380170739611907
x = 0.6214831431054627, f(x)-2.337333635039663
x = 0.6189568126763842, f(x)-2.3367096210422575
x = 0.6165431303125142, f(x)-2.336140062975938
x = 0.6142374651205752, f(x)-2.3356203840928753
x = 0.6120353465354774, f(x)-2.335146371519505
x = 0.6099324608575921, f(x)-2.3347141496710737
x = 0.6079246477437421, f(x)-2.334320155362828
x = 0.6060078966556637, f(x)-2.333961114532128
x = 0.6041783432708346, f(x)-2.3336340204886397
x = 0.6024322658614644, f(x)-2.3333361136124844
x = 0.6007660816481186, f(x)-2.3330648624228703
x = 0.5991763431349353, f(x)-2.3328179459422813
x = 0.597659734433696, f(x)-2.3325932372838647
x = 0.5962130675841733, f(x)-2.3323887883921897
x = 0.5948332788781983, f(x)-2.332202815870109
x = 0.5935174251948067, f(x)-2.3320336878269927
x = 0.5922626803536339, f(x)-2.3318799116862103
x = 0.5910663314934743, f(x)-2.331740122892279
x = 0.5899257754825892, f(x)-2.3316130744607144
x = 0.5888385153669784, f(x)-2.331497627316186
x = 0.5878021568624163, f(x)-2.3313927413671394
x = 0.5868144048956143, f(x)-2.331297467267618
x = 0.5858730601994167, f(x)-2.331210938819496
x = 0.5849760159664731, f(x)-2.3311323659708307
x = 0.5841212545653622, f(x)-2.331061028368455
x = 0.5833068443226807, f(x)-2.330996269425283
x = 0.5825309363741568, f(x)-2.330937490865106
x = 0.581791761587411, f(x)-2.3308841477098863
x = 0.5810876275585596, f(x)-2.3308357436766807
x = 0.5804169156844553, f(x)-2.330791826953417
x = 0.5797780783119777, f(x)-2.3307519863247066
x = 0.579169635965423, f(x)-2.330715847620785
x = 0.57859017465271, f(x)-2.3306830704644685
x = 0.5780383432508044, f(x)-2.330653345292741
x = 0.5775128509704762, f(x)-2.3306263906312097

In [4]:
x = np.array([0.2,1.2,1,1.4,-1.5,0.5,-0.5])
y = 3*x + 5

y

array([5.6, 8.6, 8. , 9.2, 0.5, 6.5, 3.5])

In [5]:
w = 0.3
b = 0.1
eta = 0.2

y_pred = w*x+b
y_pred

array([ 0.16,  0.46,  0.4 ,  0.52, -0.35,  0.25, -0.05])

In [6]:
err = y-y_pred
err

array([5.44, 8.14, 7.6 , 8.68, 0.85, 6.25, 3.55])

In [8]:
err_sq = err**2
err_sq

array([29.5936, 66.2596, 57.76  , 75.3424,  0.7225, 39.0625, 12.6025])

In [9]:
err_x = err*x
err_x

array([ 1.088,  9.768,  7.6  , 12.152, -1.275,  3.125, -1.775])

In [11]:
loss = np.mean(err_sq)/2
loss

np.float64(20.095935714285712)

In [13]:
dw = -np.mean(err_x)
dw

np.float64(-4.383285714285714)

In [14]:
db = -np.mean(err)
db

np.float64(-5.7871428571428565)

In [15]:
new_w = w - eta*dw
new_w

np.float64(1.1766571428571428)

In [16]:
new_b = b - eta*db
new_b

np.float64(1.2574285714285713)

In [ ]:
def gd(x, y, w, b,eta=0.2, iter=100):
    all = []
    iter_num=0
    for i in range(iter):
        iter_num +=1
        y_pred = w*x+b
        err = y-y_pred
        err_sq = err**2
        err_x = err*x
        loss = np.mean(err_sq)/2
        dw = -np.mean(err_x)
        db = -np.mean(err)
        new_w = w - eta*dw
        new_b = b - eta*db
        w = new_w
        b = new_b

        all.append([iter_num, w, b, loss, dw, db, new_w, new_b])
        if loss < 0.0001:
            break
    return pd.DataFrame(all, columns=['Iteration Num', 'w', 'b','Loss', 'dw', 'db', 'new_w', 'new_b'])

gd(x,y,w,b)

,Iteration Num,w,b,Loss,dw,db,new_w,new_b
0,1,1.176657,1.257429,20.095936,-4.383286,-5.787143,1.176657,1.257429
1,2,1.797164,2.125763,10.952998,-3.102536,-4.341670,1.797164,2.125763
2,3,2.233140,2.779654,6.009612,-2.179876,-3.269455,2.233140,2.779654
3,4,2.536583,3.274116,3.326445,-1.517218,-2.472315,2.536583,3.274116
4,5,2.745197,3.649746,1.862422,-1.043071,-1.878149,2.745197,3.649746
5,6,2.886272,3.936541,1.057980,-0.705373,-1.433975,2.886272,3.936541
6,7,2.979519,4.156707,0.611854,-0.466237,-1.100827,2.979519,4.156707
7,8,3.039143,4.326711,0.361462,-0.298119,-0.850023,3.039143,4.326711
8,9,3.075347,4.458797,0.218786,-0.181018,-0.660428,3.075347,4.458797
9,10,3.095433,4.562086,0.135968,-0.100432,-0.516447,3.095433,4.562086
10,11,3.104606,4.643397,0.086830,-0.045863,-0.406557,3.104606,4.643397
11,12,3.106551,4.707844,0.056946,-0.009724,-0.322232,3.106551,4.707844
12,13,3.103861,4.759273,0.038280,0.013448,-0.257147,3.103861,4.759273
13,14,3.098344,4.800593,0.026300,0.027584,-0.206601,3.098344,4.800593
14,15,3.091245,4.834012,0.018405,0.035494,-0.167094,3.091245,4.834012
15,16,3.083409,4.861214,0.013075,0.039183,-0.136007,3.083409,4.861214
16,17,3.075394,4.883490,0.009400,0.040071,-0.111381,3.075394,4.883490
17,18,3.067563,4.901837,0.006820,0.039159,-0.091738,3.067563,4.901837
18,19,3.060134,4.917030,0.004983,0.037143,-0.075964,3.060134,4.917030
19,20,3.053233,4.929672,0.003660,0.034505,-0.063212,3.053233,4.929672
20,21,3.046919,4.940240,0.002698,0.031570,-0.052837,3.046919,4.940240
21,22,3.041208,4.949109,0.001995,0.028557,-0.044344,3.041208,4.949109
22,23,3.036087,4.956579,0.001478,0.025605,-0.037352,3.036087,4.956579
23,24,3.031527,4.962892,0.001097,0.022799,-0.031564,3.031527,4.962892
24,25,3.027489,4.968242,0.000815,0.020190,-0.026749,3.027489,4.968242
25,26,3.023929,4.972787,0.000606,0.017800,-0.022726,3.023929,4.972787
26,27,3.020801,4.976657,0.000450,0.015637,-0.019351,3.020801,4.976657
27,28,3.018062,4.979959,0.000335,0.013696,-0.016508,3.018062,4.979959
28,29,3.015669,4.982780,0.000249,0.011967,-0.014107,3.015669,4.982780
29,30,3.013582,4.985194,0.000186,0.010436,-0.012072,3.013582,4.985194
30,31,3.011764,4.987263,0.000138,0.009085,-0.010343,3.011764,4.987263
31,32,3.010185,4.989037,0.000103,0.007899,-0.008872,3.010185,4.989037
32,33,3.008813,4.990561,0.000077,0.006859,-0.007616,3.008813,4.990561

2 features

In [34]:
x1 = np.linspace(-0.6, 0.7, 10)
x2 = np.linspace(-0.9, 0.92, 10)
y = 5 + 8*x1 + 9*x2

eta = 0.2
w1, w2, b = 0.3, 0.1, -0.3

In [36]:
def gd(x1, x2, y, w1, w2, b,eta=0.2, iter=100):
    all = []
    iter_num=0
    for i in range(iter):
        iter_num +=1
        y_pred = w1*x1 + w2*x2 + b
        err = y-y_pred
        err_sq = err**2
        err_x1 = err*x1
        err_x2 = err*x2
        loss = np.mean(err_sq)/2
        dw1 = -np.mean(err_x1)
        dw2 = -np.mean(err_x2)
        db = -np.mean(err)
        new_w1 = w1 - eta*dw1
        new_w2 = w2 - eta*dw2
        new_b = b - eta*db
        w1 = new_w1
        w2 = new_w2
        b = new_b
        all.append([iter_num, w1, w2, b, loss, dw1, dw2, db, new_w1, new_w2, new_b])
        if loss < 0.0001:
            break
    return pd.DataFrame(all, columns=['Iteration Num', 'w1', 'w2', 'b','Loss', 'dw1','dw2', 'db', 'new_w1','new_w2', 'new_b'])

gd(x1,x2,y,w1, w2,b)

,Iteration Num,w1,w2,b,Loss,dw1,dw2,db,new_w1,new_w2,new_b
0,1,1.051767,1.083185,0.854800,51.648482,-3.758833,-4.915927,-5.774000,1.051767,1.083185,0.854800
1,2,1.718245,1.961394,1.769156,38.434118,-3.332392,-4.391041,-4.571780,1.718245,1.961394,1.769156
2,3,2.309888,2.746310,2.492220,28.943456,-2.958216,-3.924583,-3.615318,2.309888,2.746310,2.492220
3,4,2.835728,3.448229,3.063184,22.033811,-2.629201,-3.509593,-2.854823,2.835728,3.448229,3.063184
4,5,3.303594,4.076233,3.513294,16.936249,-2.339326,-3.140023,-2.250547,3.303594,4.076233,3.513294
...,...,...,...,...,...,...,...,...,...,...,...
56,57,7.247615,9.506651,5.033495,0.000198,-0.008200,-0.011543,0.001046,7.247615,9.506651,5.033495
57,58,7.249088,9.508725,5.033306,0.000160,-0.007367,-0.010370,0.000942,7.249088,9.508725,5.033306
58,59,7.250412,9.510589,5.033137,0.000129,-0.006618,-0.009317,0.000848,7.250412,9.510589,5.033137
59,60,7.251601,9.512263,5.032984,0.000104,-0.005946,-0.008370,0.000763,7.251601,9.512263,5.032984
60,61,7.252670,9.513767,5.032847,0.000084,-0.005341,-0.007519,0.000687,7.252670,9.513767,5.032847

Stochastic Gradient Descent

In [46]:
x = np.array([0.2,1.2,1,1.4,-1.5,0.5,-0.5])
y = 3*x + 5

w = 0.3
b = 0.1
eta = 0.2
tol = 0.0001
n = len(x)

In [47]:
for i in range(0,50):
    for j in range(0, len(x)):
        y_pred = w*x[j] +b
        err = y[j] - y_pred
        dw, db = -(err*x[j]), -(err)
        new_w, new_b = w - eta* dw, b - eta*db
        w,b = new_w, new_b
    y_pred_all = w*x + b
    err_all = y-y_pred_all
    L = np.sum(err_all**2)/(2*n)
    print("w = ", w, ", b=", b)
    print("Loss = ", L)
    if L < tol:
        print(f'Algo stopped at {i+1}th iteration as Loss < Tolerance {tol}')
        break

w =  2.8344904011609597 , b= 4.37409141363968
Loss =  0.2439872496626577
w =  2.999644499916011 , b= 4.894869035610247
Loss =  0.005538604792553377
w =  3.003120495925965 , b= 4.978489237403861
Loss =  0.00021430224311760386
w =  3.0010085087073324 , b= 4.995150461760576
Loss =  1.0674381186758593e-05
Algo stopped at 4th iteration as Loss < Tolerance 0.0001

Mini-Batch GD

In [53]:
x = np.array([0.2,1.2,1,1.4,-1.5,0.5,-0.5])
y = 3*x + 5

w = 0.3
b = 0.1
batches = [[0,6], [3,1,5],[4,2]]
tol = 0.0001

In [54]:
for i in range(0,50):
    for j in range(0, len(x)):
        for batch in batches:
            y_pred = w*x[batch] +b
            err = y[batch] - y_pred
            dw, db = -np.sum(err*x[batch])/len(batch), -np.sum(err)/len(batch)
            new_w, new_b = w - eta* dw, b - eta*db
            w,b = new_w, new_b
    y_pred_all = w*x + b
    err_all = y-y_pred_all
    L = np.sum(err_all**2)/(2*n)
    print("w = ", w, ", b=", b)
    print("Loss = ", L)
    if L < tol:
        print(f'Algo stopped at {i+1}th iteration as Loss < Tolerance {tol}')
        break

w =  3.0079424602735796 , b= 4.972191579612213
Loss =  0.00034648090604227834
w =  3.000284231813902 , b= 4.999566868938669
Loss =  9.484121890159695e-08
Algo stopped at 2th iteration as Loss < Tolerance 0.0001