Q1. Create a DataFrame containing student information like Name, Age, Department, %Marks
Display column names of the DF
Show min/max and average marks
Get unique values and student count for each Department

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Name": ["Alpha", "Brawk", "Chronicle"],
    "Age": [20, 21, 22],
    "Department": ["DBDA", "DAC", "DBDA"],
    "Marks": [98, 87, 92]
}

In [ ]:
df = pd.DataFrame.from_dict(data)

In [ ]:
df

        Name  Age Department  Marks
0      Alpha   20       DBDA     98
1      Brawk   21        DAC     87
2  Chronicle   22       DBDA     92

In [ ]:
df["Name"]

0        Alpha
1        Brawk
2    Chronicle
Name: Name, dtype: object

In [ ]:
df["Marks"].min()

87

In [ ]:
df["Marks"].max()

98

In [ ]:
df["Marks"].mean()

92.33333333333333

In [ ]:
df["Department"].unique()

array(['DBDA', 'DAC'], dtype=object)

In [ ]:
df.Department.value_counts()

Department
DBDA    2
DAC     1
Name: count, dtype: int64

Q2. Read csv file solar.csv
1. Display all the plants with capacity > 500 MW
2. Display plant details for New York plant
3. For all the plants display Average MW Per Plant and Generation (GWh)
4. Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)
5. List top 5 plants for their Generation
6. Display all plant details for states – California, Nevada, Arizona and Texas
7. Group the plants by region, find – min/max capacity plant for each group
8. Add following information to the existing details for the plants 

    North Carolina    148    669    4.5    1162     North

In [ ]:
df = pd.read_csv("C:/Users/dbda.STUDENTSDC/Downloads/solar.csv")

In [ ]:
df = df.set_index("State")

In [ ]:
df

,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
State,,,,,
California,289,4395,15.3,10826,West
Arizona,48,1078,22.5,2550,West
Nevada,11,238,21.6,557,West
Chicago,33,261,7.9,590,North
Connecticut,20,118,5.9,235,East
Texas,12,187,15.6,354,South
New York,13,53,4.1,84,East
Florida,15,535,12.3,453,South

In [ ]:
df[df["Installed Capacity (MW)"]>500]

,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
State,,,,,
California,289,4395,15.3,10826,West
Arizona,48,1078,22.5,2550,West
Florida,15,535,12.3,453,South

In [ ]:
df.loc["New York"]

Number of Solar Plants       13
Installed Capacity (MW)      53
Average MW Per Plant        4.1
Generation (GWh)             84
Region                     East
Name: New York, dtype: object

In [ ]:
df[col_names = ["Average MW Per Plant", "Generation (GWh)"]]
df

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (810878001.py, line 1)