In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from tqdm import tqdm
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report, roc_curve, RocCurveDisplay, roc_auc_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import log_loss

import os

os.chdir('C:/Users/dbda.STUDENTSDC/Desktop/M.L/Datasets/')

In [18]:
wisconsin = pd.read_csv('C:/Users/dbda.STUDENTSDC/Desktop/M.L/Cases/Wisconsin/BreastCancer.csv', index_col=0)
wisconsin

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,Benign
63375,9,1,2,6,4,10,7,7,2,Malignant
76389,10,4,7,2,2,8,6,1,1,Malignant
95719,6,10,10,10,8,10,7,10,7,Malignant
128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...
1369821,10,10,10,10,5,10,10,10,7,Malignant
1371026,5,10,10,10,4,10,5,6,3,Malignant
1371920,5,1,1,1,2,1,3,2,1,Benign
8233704,4,1,1,1,1,1,2,1,1,Benign
13454352,1,1,3,1,2,1,2,1,1,Benign

In [19]:
le = LabelEncoder()
wisconsin['Class'] = le.fit_transform(wisconsin['Class'])
wisconsin

,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
Code,,,,,,,,,,
61634,5,4,3,1,2,2,2,3,1,0
63375,9,1,2,6,4,10,7,7,2,1
76389,10,4,7,2,2,8,6,1,1,1
95719,6,10,10,10,8,10,7,10,7,1
128059,1,1,1,1,2,5,5,1,1,0
...,...,...,...,...,...,...,...,...,...,...
1369821,10,10,10,10,5,10,10,10,7,1
1371026,5,10,10,10,4,10,5,6,3,1
1371920,5,1,1,1,2,1,3,2,1,0
8233704,4,1,1,1,1,1,2,1,1,0
13454352,1,1,3,1,2,1,2,1,1,0

In [ ]:
le = LabelEncoder()
x, y = wisconsin.drop('Class', axis=1), wisconsin['Class']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=25, stratify = y)

In [21]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))
y_pred_prob = knn.predict_proba(x_test)
print('ROC AUC: ', roc_auc_score(y_test, y_pred_prob[:,1]))

Accuracy Score:  0.9761904761904762
ROC AUC:  0.9908917069243157

In [22]:
for i in range(1, 10):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train, y_train)
    y_pred = knn.predict(x_test)
    print("When neighbors = ", i)
    print('Accuracy Score: ', accuracy_score(y_test, y_pred))
    y_pred_prob = knn.predict_proba(x_test)
    print('ROC AUC: ', roc_auc_score(y_test, y_pred_prob[:,1]))
    print('\n')

When neighbors =  1
Accuracy Score:  0.9571428571428572
ROC AUC:  0.9474637681159419


When neighbors =  2
Accuracy Score:  0.9333333333333333
ROC AUC:  0.9806260064412239


When neighbors =  3
Accuracy Score:  0.9714285714285714
ROC AUC:  0.9841988727858293


When neighbors =  4
Accuracy Score:  0.9619047619047619
ROC AUC:  0.9911936392914654


When neighbors =  5
Accuracy Score:  0.9761904761904762
ROC AUC:  0.9908917069243157


When neighbors =  6
Accuracy Score:  0.9523809523809523
ROC AUC:  0.9907910628019324


When neighbors =  7
Accuracy Score:  0.9619047619047619
ROC AUC:  0.9908413848631239


When neighbors =  8
Accuracy Score:  0.9619047619047619
ROC AUC:  0.9906400966183575


When neighbors =  9
Accuracy Score:  0.9619047619047619
ROC AUC:  0.9904891304347826

In [ ]:
hr = pd.read_csv('C:/Users/dbda.STUDENTSDC/Desktop/M.L/Datasets/HR_comma_sep.csv')

le = LabelEncoder()
hr['left'] = le.fit_transform(hr['left'])
le.classes_
x,y = hr.drop('left',axis=1),hr['left']
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=25, stratify = y)
hr.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low

In [28]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print('Accuracy Score: ', accuracy_score(y_test, y_pred))
y_pred_prob = knn.predict_proba(x_test)
print('ROC AUC: ', roc_auc_score(y_test, y_pred_prob[:,1]))

ValueError: could not convert string to float: 'RandD'

In [29]:
for i in range(1, 10):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train, y_train)
    y_pred = knn.predict(x_test)
    print("When neighbors = ", i)
    print('Accuracy Score: ', accuracy_score(y_test, y_pred))
    y_pred_prob = knn.predict_proba(x_test)
    print('ROC AUC: ', roc_auc_score(y_test, y_pred_prob[:,1]))
    print('\n')

ValueError: could not convert string to float: 'RandD'