In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer,make_column_selector
import os

#### Boston Data

In [2]:
boston = pd.read_csv("Datasets/Boston.csv")
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [3]:
X = boston.drop('medv', axis=1)
y = boston["medv"]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [5]:
aplhas = [0.001, 0.01, 0.1, 1, 1.5, 2.5, 5, 10]
scores = []
for a in aplhas:
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'score'])
df_scores.sort_values('score')

    alpha     score
1   0.010  3.088221
0   0.001  3.114200
2   0.100  3.129219
3   1.000  3.373066
4   1.500  3.542921
5   2.500  3.632183
6   5.000  3.856294
7  10.000  3.942140

#### housing

In [1]:
hous = pd.read_csv('Datasets/Housing.csv')
X, y = hous.drop('price', axis=1), hous['price']
hous

NameError: name 'pd' is not defined

In [7]:
ohe = OneHotEncoder(drop='first', sparse_output=False).set_output(transform='pandas')
col_trnf = ColumnTransformer([('OHE', ohe, list(hous.columns[hous.dtypes == object]))],
                             remainder = 'passthrough',
                             verbose_feature_names_out=False)
col_trnf = col_trnf.set_output(transform='pandas')
hous = col_trnf.fit_transform(hous)
hous.head()

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,42000.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,38500.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,49500.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,60500.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,61000.0,6360,2,1,1,0

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [10]:
aplhas = [0.001, 0.01, 0.1, 1, 1.5, 2.5, 5, 10]
scores = []
for a in aplhas:
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, mean_absolute_error(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha', 'score'])
df_scores.sort_values('score')

    alpha         score
7  10.000  11594.596229
6   5.000  11597.777786
5   2.500  11599.368564
4   1.500  11599.989301
3   1.000  11600.307457
2   0.100  11600.878772
1   0.010  11600.935421
0   0.001  11600.941078