In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error
from sklearn.preprocessing import PolynomialFeatures
import os

In [ ]:
pizza = pd.read_csv("Datasets/pizza.csv")
pizza.head()

   Promote  Sales
0       23    554
1       56   1339
2       34    815
3       25    609
4       67   1600

In [4]:
X, y = pizza[['Promote']], pizza['Sales']

In [ ]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
lr = LinearRegression()
lr.fit(X_poly, y)
lr.intercept_, lr.coef_

Insurance

In [ ]:
insure = pd.

#### Boston
1. train-test_split the dataset
2. Test MAE for degrees = 2,3,4

here we checked wioith different caues of degree to check which gives lowest MAE

In [2]:
boston = pd.read_csv("Datasets/Boston.csv")
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [3]:
X = boston.drop('medv', axis=1)
y = boston["medv"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [18]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly_train = poly.fit_transform(X_train)
X_poly_test = poly.transform(X_test)
lr = LinearRegression()
lr.fit(X_poly_train, y_train)
y_pred = lr.predict(X_poly_test)
mean_absolute_error(y_test, y_pred)

2.6635485505319316

#### Housing

In [20]:
housing = pd.read_csv('Datasets/Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

As here we have different coloumns that have categorical values
So we use the One-Hot encoding

In [23]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [25]:
#this should not be done as It is nto making one hot encoding only for categorical coloumns but also for the differet numerical coloumns and making 521 coloumns after encoding 
#for every price

ohe = OneHotEncoder(drop='first', sparse_output=False).set_output(transform='pandas')
ohe.fit_transform(housing)

,price_25245.0,price_26000.0,price_26500.0,price_27000.0,price_28000.0,price_30000.0,price_30500.0,price_31900.0,price_32000.0,price_32500.0,...,stories_4,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,garagepl_1,garagepl_2,garagepl_3,prefarea_yes
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
542,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
543,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
544,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
545,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [29]:
#checking the coloumns having only object values
cat_hous = housing[housing.columns[housing.dtypes == object]]
num_hous = housing[housing.columns[housing.dtypes != object]]

In [48]:

ohe = OneHotEncoder(drop='first', sparse_output=False).set_output(transform='pandas')
ohe_hous = ohe.fit_transform(cat_hous)
hous = pd.concat([ohe_hous, num_hous], axis=1)
X, y = hous.drop('price', axis=1), hous['price']
hous.head()

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,42000.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,38500.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,49500.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,60500.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,61000.0,6360,2,1,1,0

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [49]:
poly = PolynomialFeatures(degree=1, include_bias=False).set_output(transform='pandas')
X_poly_train = poly.fit_transform(X_train)
X_poly_test = poly.transform(X_test)
lr = LinearRegression()
lr.fit(X_poly_train, y_train)
y_pred = lr.predict(X_poly_test)
mean_absolute_error(y_test, y_pred)

11463.135922494639

In [ ]:
#performing best way to work with categorical data
ohe = OneHotEncoder(drop='first', sparse_output=False).set_output(transform='pandas')
col_trnf = ColumnTransformer([('OHE', ohe, list(housing.columns[housing.dtypes == object]))],
                             remainder = 'passthrough',
                             verbose_feature_names_out=False)
col_trnf = col_trnf.set_output(transform='pandas')
hous = col_trnf.fit_transform(housing)

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,42000.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,38500.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,49500.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,60500.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,61000.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,91500.0,4800,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,94000.0,6000,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,103000.0,6000,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,105000.0,6000,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,105000.0,6000,3,1,2,1

In [51]:
X, y = hous.drop('price', axis=1), hous['price']

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [53]:
poly = PolynomialFeatures(degree=1, include_bias=False).set_output(transform='pandas')
X_poly_train = poly.fit_transform(X_train)
X_poly_test = poly.transform(X_test)
lr = LinearRegression()
lr.fit(X_poly_train, y_train)
y_pred = lr.predict(X_poly_test)
mean_absolute_error(y_test, y_pred)

11600.941705536463

#### Exp_salaries

In [55]:
#Same can be done with exp_salaries and salaries
sals = pd.read_csv("Datasets/Exp_Salaries.csv")
X, y = sals.drop('Salary', axis=1), sals['Salary']

In [59]:
from sklearn.compose import make_column_selector

ohe = OneHotEncoder(drop='first', sparse_output=False).set_output(transform='pandas')
col_trnf = ColumnTransformer([('OHE', ohe, make_column_selector(dtype_include = object))],
                             remainder = 'passthrough',
                             verbose_feature_names_out=False)
col_trnf = col_trnf.set_output(transform='pandas')
X = col_trnf.fit_transform(X)

In [ ]:
#do as above after this